---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lejing.
--- DateTime: 2026/9/2 12:29
---

Player = Object:extend()

function Player:init(args)
    self.x = args.x
    self.y = args.y
    self.radius = args.radius
    self.speed = args.speed
end
