---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lejing.
--- DateTime: 2026/9/2 12:29
---

Player = Object:extend()
Player:implement(GameObject)
Player:implement(Physics)
Player:implement(Unit)

function Player:init(args)
    self:init_game_object(args)
    self:init_physics(args)
    self:init_unit(args)
    self:set_as_rectangle(9, 9, "dynamic", "player")
    self.color = self.color or {218 / 255, 218 / 255, 218 / 255, 1}
    self.shadow_color = self.shadow_color or {0, 0, 0, 0.35}
end

function Player:update(dt)
    local dx, dy = 0, 0

    if love.keyboard.isDown("left", "a") then dx = dx - 1 end
    if love.keyboard.isDown("right", "d") then dx = dx + 1 end
    if love.keyboard.isDown("up", "w") then dy = dy - 1 end
    if love.keyboard.isDown("down", "s") then dy = dy + 1 end

    local length = math.sqrt(dx * dx + dy * dy)
    if length > 0 then
        dx, dy = dx / length, dy / length
    end

    self:set_velocity(dx * self.mvspd, dy * self.mvspd)
    self:update_game_object(dt)
    self:keep_inside(0, 0, gw, gh)
end

function Player:draw()
    graphics.rectangle(
        self.x + 1.5,
        self.y + 1.5,
        self.width,
        self.height,
        3,
        3,
        self.shadow_color
    )
    graphics.rectangle(self.x, self.y, self.width, self.height, 3, 3, self.color)

    local arrow_x = self.x + 0.9 * self.width
    graphics.line(arrow_x + 3, self.y, arrow_x, self.y - 3, self.color, 1)
    graphics.line(arrow_x + 3, self.y, arrow_x, self.y + 3, self.color, 1)
end
